site_name: My Docs
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
repo_name: sohtsuka/mkdocs-sandbox
repo_url: https://github.com/sohtsuka/mkdocs-sandbox
edit_uri: edit/main/docs/
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 
          name: Japanese (日本語)
          site_name: 私のドキュメント
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 
  - admonition