site_name: My Docs
theme:
  name: material
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 
          name: Japanese (日本語)
          site_name: 私のドキュメント
