site_name: My Docs
theme:
  name: material
repo_name: sohtsuka/mkdocs-sandbox
repo_url: https://github.com/sohtsuka/mkdocs-sandbox
edit_uri: edit/main/docs/
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 
          name: Japanese (日本語)
          site_name: 私のドキュメント
